### ISSUE TITLE
Build error related to automake

### ISSUE THREAD

**Issue by fusion809** [JeffHoogland/ecomp#2]
Hi,

I have run:

``` sh
./autogen.sh --prefix=/usr
```

from this repo and it returned the error documented [here](http://paste2.org/pPbLVxEk). Oh and btw, I have received this error on both Arch Linux and Sabayon. 

Thanks for your time,
Brenton

**Comment by JeffHoogland** [comment]
Make sure the build directory is clean with **make distclean** and perhaps try running **autoreconf** to adjust for your auto tools version.

**Comment by fusion809** [comment]
Now I'm getting the same error under Debian 8.2, and running `make distclean` is making no difference (it just gives an error `make: *** No rule to make target 'distclean'.  Stop.`). Running `autoreconf` gives the same error again as `./autogen.sh --prefix=/usr`.

**Comment by JeffHoogland** [comment]
Honestly not sure - it works as expected on Ubuntu 14.04 which is the only platform I'm officially supporting this module on currently. Patches welcome.

**Comment by rbtylee** [comment]
The error

`Makefile.am: error: required file './README' not found`

Can be fixed simply by either renaming README.md as README or by creating a file README.

Or perhaps better [pass the foreign option to automake](http://stackoverflow.com/questions/15013672/use-autotools-with-readme-md).

**Comment by rbtylee** [comment]
Commit 615156f should fix this issues on more modern platforms.
